apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/creator: ra38697@gmail.com
    run.googleapis.com/lastModifier: ra38697@gmail.com
    run.googleapis.com/operation-id: 067ae762-3a6b-4a93-ae4c-6a4a23a34e8a
  creationTimestamp: '2025-09-02T12:10:05.160087Z'
  generation: 67
  labels:
    cloud.googleapis.com/location: europe-west2
    run.googleapis.com/lastUpdatedTime: '2025-09-04T14:48:37.897075Z'
    run.googleapis.com/satisfiesPzs: 'true'
  name: cragcast-upsert
  namespace: '898934496030'
  resourceVersion: AAY9+tEJgSA
  selfLink: /apis/run.googleapis.com/v1/namespaces/898934496030/jobs/cragcast-upsert
  uid: 04a456cc-2dc9-4201-ad1c-96b2406766fb
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/execution-environment: gen2
      labels:
        client.knative.dev/nonce: hit_tig_zef
    spec:
      taskCount: 1
      template:
        spec:
          containers:
          - args:
            - -m
            - jobs.weather_updater.upsert.run_upsert
            command:
            - python
            env:
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: WINDOW_HOURS
              value: '1'
            - name: MAX_ROWS_PER_RUN
              value: '50000'
            - name: TOTAL_SHARDS
              value: '1'
            - name: SHARD_INDEX
              value: '0'
            - name: CHUNK_SIZE
              value: '200'
            - name: PARTIAL_WINDOW_POLICY
              value: allow
            - name: STAGING_RETRY_MODE
              value: new_batch
            - name: WINDOW_SAFETY_MIN
              value: '10'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DATABASE_URL
            image: europe-west2-docker.pkg.dev/winged-woods-468712-j1/cragcast/cragcast-upsert:20250903-224621
            name: cragcast-upsert-1
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
            volumeMounts:
            - mountPath: /certs
              name: crdb-ca
          maxRetries: 3
          serviceAccountName: crag-etl@winged-woods-468712-j1.iam.gserviceaccount.com
          timeoutSeconds: '1800'
          volumes:
          - name: crdb-ca
            secret:
              items:
              - key: latest
                path: root.crt
              secretName: CRDB_CA
status:
  conditions:
  - lastTransitionTime: '2025-09-03T21:50:30.439110Z'
    status: 'True'
    type: Ready
  executionCount: 68
  latestCreatedExecution:
    completionStatus: EXECUTION_SUCCEEDED
    completionTimestamp: '2025-09-04T11:36:12.557497Z'
    creationTimestamp: '2025-09-04T11:33:48.567778Z'
    name: cragcast-upsert-sdffh
  observedGeneration: 67
